<?php

$sendXML = '<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body>
<StandardBusinessDocuments>
<sh:StandardBusinessDocument xmlns:sh="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader" xmlns:order="urn:ean.ucc:order:2" xmlns:eanucc="urn:ean.ucc:2" xmlns:ns0="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<sh:StandardBusinessDocumentHeader>
<sh:HeaderVersion>2.4.0</sh:HeaderVersion>
<sh:Sender>
<sh:Identifier Authority="EAN.UCC">6001000000001</sh:Identifier>
</sh:Sender>
<sh:Receiver>
<sh:Identifier Authority="EAN.UCC">6001007802929</sh:Identifier>
</sh:Receiver>
<sh:DocumentIdentification>
<sh:Standard>EAN.UCC</sh:Standard>
<sh:TypeVersion>2.4</sh:TypeVersion>
<sh:InstanceIdentifier>401149639</sh:InstanceIdentifier>
<sh:Type>ROSTER</sh:Type>
<sh:MultipleType>false</sh:MultipleType>
<sh:CreationDateAndTime>2014-06-02T16:09:43</sh:CreationDateAndTime>
</sh:DocumentIdentification>
</sh:StandardBusinessDocumentHeader>
<eanucc:message>
<entityIdentification>
<uniqueCreatorIdentification>0478813499</uniqueCreatorIdentification>
<contentOwner>
<gln>6001000000001</gln>
</contentOwner>
</entityIdentification>
<eanucc:transaction>
<entityIdentification>
<uniqueCreatorIdentification>0478813499</uniqueCreatorIdentification>
<contentOwner>
<gln>6001000000001</gln>
</contentOwner>
</entityIdentification>
<command>
<eanucc:documentCommand>
<documentCommandHeader type="ADD">
<entityIdentification>
<uniqueCreatorIdentification>0478813499</uniqueCreatorIdentification>
<contentOwner>
<gln>6001000000001</gln>
</contentOwner>
</entityIdentification>
</documentCommandHeader>
<documentCommandOperand>
<order:order creationDateTime="2014-06-02T00:00:00" documentStatus="ORIGINAL">
<orderIdentification>
<uniqueCreatorIdentification>0478813499</uniqueCreatorIdentification>
<contentOwner>
<gln>6001000000001</gln>
<additionalPartyIdentification>
<additionalPartyIdentificationValue />
<additionalPartyIdentificationType>ROSTER</additionalPartyIdentificationType>
</additionalPartyIdentification>
</contentOwner>
</orderIdentification>
<orderPartyInformation>
<seller>
<gln>6006507000004</gln>
<additionalPartyIdentification>
<additionalPartyIdentificationValue>1000000066</additionalPartyIdentificationValue>
<additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
</additionalPartyIdentification>
<additionalPartyIdentification>
<additionalPartyIdentificationValue>Cape Herb And Spice (Pty) Ltd</additionalPartyIdentificationValue>
<additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
</additionalPartyIdentification>
<additionalPartyIdentification>
<additionalPartyIdentificationValue>4830249845</additionalPartyIdentificationValue>
<additionalPartyIdentificationType>SELLER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
</additionalPartyIdentification>
</seller>
<buyer>
<gln>6001007032005</gln>
<additionalPartyIdentification>
<additionalPartyIdentificationValue>Western Cape Franchise</additionalPartyIdentificationValue>
<additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
</additionalPartyIdentification>
</buyer>
</orderPartyInformation>
<orderLogisticalInformation>
<shipToLogistics>
<shipTo>
<gln>6001007032128</gln>
<additionalPartyIdentification>
<additionalPartyIdentificationValue>WF12</additionalPartyIdentificationValue>
<additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
</additionalPartyIdentification>
<additionalPartyIdentification>
<additionalPartyIdentificationValue>Family Welgemoed</additionalPartyIdentificationValue>
<additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
</additionalPartyIdentification>
<additionalPartyIdentification>
<additionalPartyIdentificationValue>WF12</additionalPartyIdentificationValue>
<additionalPartyIdentificationType>DELIVERY_ID</additionalPartyIdentificationType>
</additionalPartyIdentification>
<additionalPartyIdentification>
<additionalPartyIdentificationValue>FAMILY WELGEMOED</additionalPartyIdentificationValue>
<additionalPartyIdentificationType>DELIVERY_NAME</additionalPartyIdentificationType>
</additionalPartyIdentification>
<additionalPartyIdentification>
<additionalPartyIdentificationValue>WELGEMOED SHOPPING CENTRE KOMMASSARIS STREET</additionalPartyIdentificationValue>
<additionalPartyIdentificationType>DELIVERY_STREET</additionalPartyIdentificationType>
</additionalPartyIdentification>
<additionalPartyIdentification>
<additionalPartyIdentificationValue>WELGEMOED, BELLVILLE</additionalPartyIdentificationValue>
<additionalPartyIdentificationType>DELIVERY_CITY</additionalPartyIdentificationType>
</additionalPartyIdentification>
<additionalPartyIdentification>
<additionalPartyIdentificationValue>7530</additionalPartyIdentificationValue>
<additionalPartyIdentificationType>DELIVERY_POSTALCODE</additionalPartyIdentificationType>
</additionalPartyIdentification>
<additionalPartyIdentification>
<additionalPartyIdentificationValue>021 913 2350</additionalPartyIdentificationValue>
<additionalPartyIdentificationType>DELIVERY_TELEPHONE</additionalPartyIdentificationType>
</additionalPartyIdentification>
<additionalPartyIdentification>
<additionalPartyIdentificationValue>021 913 4741</additionalPartyIdentificationValue>
<additionalPartyIdentificationType>DELIVERY_FAX</additionalPartyIdentificationType>
</additionalPartyIdentification>
</shipTo>
</shipToLogistics>
<orderLogisticalDateGroup>
<requestedDeliveryDateAtUltimateConsignee>
<date>2014-06-04</date>
</requestedDeliveryDateAtUltimateConsignee>
</orderLogisticalDateGroup>
</orderLogisticalInformation>
<orderLineItem number="10">
<requestedQuantity>
<value>1.000</value>
</requestedQuantity>
<netPrice>
<amount>
<currencyCode>
<currencyISOCode>ZAR</currencyISOCode>
</currencyCode>
<monetaryAmount>130.97</monetaryAmount>
</amount>
</netPrice>
<netAmount>
<amount>
<currencyCode>
<currencyISOCode>ZAR</currencyISOCode>
</currencyCode>
<monetaryAmount>149.31</monetaryAmount>
</amount>
</netAmount>
<tradeItemIdentification>
<gtin>16006507004764</gtin>
<additionalTradeItemIdentification>
<additionalTradeItemIdentificationValue>SETB0000001</additionalTradeItemIdentificationValue>
<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
</additionalTradeItemIdentification>
<additionalTradeItemIdentification>
<additionalTradeItemIdentificationValue>CAPE HERB SALT&amp;PEPPER GRINDER SET 110GR</additionalTradeItemIdentificationValue>
<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
</additionalTradeItemIdentification>
<additionalTradeItemIdentification>
<additionalTradeItemIdentificationValue>493004</additionalTradeItemIdentificationValue>
<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
</additionalTradeItemIdentification>
<additionalTradeItemIdentification>
<additionalTradeItemIdentificationValue>6</additionalTradeItemIdentificationValue>
<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
</additionalTradeItemIdentification>
</tradeItemIdentification>
</orderLineItem>
<orderLineItem number="20">
<requestedQuantity>
<value>1.000</value>
</requestedQuantity>
<netPrice>
<amount>
<currencyCode>
<currencyISOCode>ZAR</currencyISOCode>
</currencyCode>
<monetaryAmount>93.83</monetaryAmount>
</amount>
</netPrice>
<netAmount>
<amount>
<currencyCode>
<currencyISOCode>ZAR</currencyISOCode>
</currencyCode>
<monetaryAmount>106.97</monetaryAmount>
</amount>
</netAmount>
<tradeItemIdentification>
<gtin>16006507005006</gtin>
<additionalTradeItemIdentification>
<additionalTradeItemIdentificationValue>RUBTB000002</additionalTradeItemIdentificationValue>
<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
</additionalTradeItemIdentification>
<additionalTradeItemIdentification>
<additionalTradeItemIdentificationValue>CAPE HERB RUB PORTU PERI PERI 100GR</additionalTradeItemIdentificationValue>
<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
</additionalTradeItemIdentification>
<additionalTradeItemIdentification>
<additionalTradeItemIdentificationValue>538724</additionalTradeItemIdentificationValue>
<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
</additionalTradeItemIdentification>
<additionalTradeItemIdentification>
<additionalTradeItemIdentificationValue>6</additionalTradeItemIdentificationValue>
<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
</additionalTradeItemIdentification>
</tradeItemIdentification>
</orderLineItem>
<orderLineItem number="30">
<requestedQuantity>
<value>1.000</value>
</requestedQuantity>
<netPrice>
<amount>
<currencyCode>
<currencyISOCode>ZAR</currencyISOCode>
</currencyCode>
<monetaryAmount>90.75</monetaryAmount>
</amount>
</netPrice>
<netAmount>
<amount>
<currencyCode>
<currencyISOCode>ZAR</currencyISOCode>
</currencyCode>
<monetaryAmount>103.46</monetaryAmount>
</amount>
</netAmount>
<tradeItemIdentification>
<gtin>16006507005068</gtin>
<additionalTradeItemIdentification>
<additionalTradeItemIdentificationValue>FSSHB000004</additionalTradeItemIdentificationValue>
<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
</additionalTradeItemIdentification>
<additionalTradeItemIdentification>
<additionalTradeItemIdentificationValue>CAPE HERB SMOKY BBQ SEASONING 245GR</additionalTradeItemIdentificationValue>
<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
</additionalTradeItemIdentification>
<additionalTradeItemIdentification>
<additionalTradeItemIdentificationValue>467728</additionalTradeItemIdentificationValue>
<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
</additionalTradeItemIdentification>
<additionalTradeItemIdentification>
<additionalTradeItemIdentificationValue>6</additionalTradeItemIdentificationValue>
<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
</additionalTradeItemIdentification>
</tradeItemIdentification>
</orderLineItem>
<orderHeaderIndicator>
<isApplicationReceiptAcknowledgementRequired>true</isApplicationReceiptAcknowledgementRequired>
<isOrderFreeOfExciseTaxDuty>false</isOrderFreeOfExciseTaxDuty>
</orderHeaderIndicator>
</order:order>
</documentCommandOperand>
</eanucc:documentCommand>
</command>
</eanucc:transaction>
</eanucc:message>
</sh:StandardBusinessDocument>
</StandardBusinessDocuments>
</soap:Body>
</soap:Envelope>';


?>