<?php

$sendXML = '<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP:Header/>
	<SOAP:Body>
		<sh:StandardBusinessDocument xmlns:sh="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader" xmlns:order="urn:ean.ucc:order:2" xmlns:eanucc="urn:ean.ucc:2" xmlns:ns0="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<sh:StandardBusinessDocumentHeader>
				<sh:HeaderVersion>2.4.0</sh:HeaderVersion>
				<sh:Sender>
					<sh:Identifier Authority="EAN.UCC">6001000000001</sh:Identifier>
				</sh:Sender>
				<sh:Receiver>
					<sh:Identifier Authority="EAN.UCC">6001007802929</sh:Identifier>
				</sh:Receiver>
				<sh:DocumentIdentification>
					<sh:Standard>EAN.UCC</sh:Standard>
					<sh:TypeVersion>2.4</sh:TypeVersion>
					<sh:InstanceIdentifier>128991807</sh:InstanceIdentifier>
					<sh:Type>ROSTER</sh:Type>
					<sh:MultipleType>false</sh:MultipleType>
					<sh:CreationDateAndTime>2011-10-14T16:43:54</sh:CreationDateAndTime>
				</sh:DocumentIdentification>
			</sh:StandardBusinessDocumentHeader>
			<eanucc:message>
				<entityIdentification>
					<uniqueCreatorIdentification>0426541407</uniqueCreatorIdentification>
					<contentOwner>
						<gln>6001000000001</gln>
					</contentOwner>
				</entityIdentification>
				<eanucc:transaction>
					<entityIdentification>
						<uniqueCreatorIdentification>0426541407</uniqueCreatorIdentification>
						<contentOwner>
							<gln>6001000000001</gln>
						</contentOwner>
					</entityIdentification>
					<command>
						<eanucc:documentCommand>
							<documentCommandHeader type="ADD">
								<entityIdentification>
									<uniqueCreatorIdentification>0426541407</uniqueCreatorIdentification>
									<contentOwner>
										<gln>6001000000001</gln>
									</contentOwner>
								</entityIdentification>
							</documentCommandHeader>
							<documentCommandOperand>
								<order:order creationDateTime="2011-10-11T00:00:00" documentStatus="ORIGINAL">
									<orderIdentification>
										<uniqueCreatorIdentification>0426541407</uniqueCreatorIdentification>
										<contentOwner>
											<gln>6001000000001</gln>
											<additionalPartyIdentification>
												<additionalPartyIdentificationValue/>
												<additionalPartyIdentificationType>ROSTER</additionalPartyIdentificationType>
											</additionalPartyIdentification>
										</contentOwner>
									</orderIdentification>
									<orderPartyInformation>
										<seller>
											<gln>6003105000009</gln>
											<additionalPartyIdentification>
												<additionalPartyIdentificationValue>0010005890</additionalPartyIdentificationValue>
												<additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
											</additionalPartyIdentification>
											<additionalPartyIdentification>
												<additionalPartyIdentificationValue>Paarmans Foods (Pty) Ltd</additionalPartyIdentificationValue>
												<additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
											</additionalPartyIdentification>
											<additionalPartyIdentification>
												<additionalPartyIdentificationValue>4530101874</additionalPartyIdentificationValue>
												<additionalPartyIdentificationType>SELLER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
											</additionalPartyIdentification>
										</seller>
										<buyer>
											<gln>6001007031006</gln>
											<additionalPartyIdentification>
												<additionalPartyIdentificationValue>Western Cape Corporate</additionalPartyIdentificationValue>
												<additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
											</additionalPartyIdentification>
										</buyer>
									</orderPartyInformation>
									<orderLogisticalInformation>
										<shipToLogistics>
											<shipTo>
												<gln>6001007031992</gln>
												<additionalPartyIdentification>
													<additionalPartyIdentificationValue>WC14</additionalPartyIdentificationValue>
													<additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
												</additionalPartyIdentification>
												<additionalPartyIdentification>
													<additionalPartyIdentificationValue>Canalwalk</additionalPartyIdentificationValue>
													<additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
												</additionalPartyIdentification>
											</shipTo>
										</shipToLogistics>
										<orderLogisticalDateGroup>
											<requestedDeliveryDateAtUltimateConsignee>
												<date>2011-10-18</date>
											</requestedDeliveryDateAtUltimateConsignee>
										</orderLogisticalDateGroup>
									</orderLogisticalInformation>
									<orderLineItem number="10">
										<requestedQuantity>
											<value>5.000</value>
										</requestedQuantity>
										<netPrice>
											<amount>
												<currencyCode>
													<currencyISOCode>ZAR</currencyISOCode>
												</currencyCode>
												<monetaryAmount>134.40</monetaryAmount>
											</amount>
										</netPrice>
										<netAmount>
											<amount>
												<currencyCode>
													<currencyISOCode>ZAR</currencyISOCode>
												</currencyCode>
												<monetaryAmount>766.10</monetaryAmount>
											</amount>
										</netAmount>
										<tradeItemIdentification>
											<gtin>26003105000515</gtin>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>201</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>INA PAARMAN"S DINKY HERB DRESSING 50ML</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>145164</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>48</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
										</tradeItemIdentification>
									</orderLineItem>
									<orderLineItem number="20">
										<requestedQuantity>
											<value>8.000</value>
										</requestedQuantity>
										<netPrice>
											<amount>
												<currencyCode>
													<currencyISOCode>ZAR</currencyISOCode>
												</currencyCode>
												<monetaryAmount>133.80</monetaryAmount>
											</amount>
										</netPrice>
										<netAmount>
											<amount>
												<currencyCode>
													<currencyISOCode>ZAR</currencyISOCode>
												</currencyCode>
												<monetaryAmount>1220.24</monetaryAmount>
											</amount>
										</netAmount>
										<tradeItemIdentification>
											<gtin>16003105002628</gtin>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>602190070</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>INA PAARMAN"S 1000ISLAND SAL/DRESS 300ML</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>312317</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>12</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
										</tradeItemIdentification>
									</orderLineItem>
									<orderLineItem number="30">
										<requestedQuantity>
											<value>12.000</value>
										</requestedQuantity>
										<netPrice>
											<amount>
												<currencyCode>
													<currencyISOCode>ZAR</currencyISOCode>
												</currencyCode>
												<monetaryAmount>168.00</monetaryAmount>
											</amount>
										</netPrice>
										<netAmount>
											<amount>
												<currencyCode>
													<currencyISOCode>ZAR</currencyISOCode>
												</currencyCode>
												<monetaryAmount>2298.24</monetaryAmount>
											</amount>
										</netAmount>
										<tradeItemIdentification>
											<gtin>16003105003052</gtin>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>602190170</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>INA PAARMAN"S FRENCH VINAIGRETTE 300ML</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>410413</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>12</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
										</tradeItemIdentification>
									</orderLineItem>
									<orderLineItem number="40">
										<requestedQuantity>
											<value>6.000</value>
										</requestedQuantity>
										<netPrice>
											<amount>
												<currencyCode>
													<currencyISOCode>ZAR</currencyISOCode>
												</currencyCode>
												<monetaryAmount>163.20</monetaryAmount>
											</amount>
										</netPrice>
										<netAmount>
											<amount>
												<currencyCode>
													<currencyISOCode>ZAR</currencyISOCode>
												</currencyCode>
												<monetaryAmount>1116.30</monetaryAmount>
											</amount>
										</netAmount>
										<tradeItemIdentification>
											<gtin>16003105003021</gtin>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>602070920</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>INA PAARMAN"S CHOCOLATE ICING KIT 250GR</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>398967</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
											<additionalTradeItemIdentification>
												<additionalTradeItemIdentificationValue>12</additionalTradeItemIdentificationValue>
												<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
											</additionalTradeItemIdentification>
										</tradeItemIdentification>
									</orderLineItem>
									<orderHeaderIndicator>
										<isApplicationReceiptAcknowledgementRequired>true</isApplicationReceiptAcknowledgementRequired>
										<isOrderFreeOfExciseTaxDuty>false</isOrderFreeOfExciseTaxDuty>
									</orderHeaderIndicator>
								</order:order>
							</documentCommandOperand>
						</eanucc:documentCommand>
					</command>
				</eanucc:transaction>
			</eanucc:message>
		</sh:StandardBusinessDocument>
	</SOAP:Body>
</SOAP:Envelope>';


?>