<?php

$sendXML = '<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP:Header>
	  <sh:BasicAuth xmlns:sh="http://soap-authentication.org/basic/2001/10/" SOAP:mustUnderstand="1">
         <Name>username</Name>
         <Password>password</Password>
      </sh:BasicAuth>
    </SOAP:Header>
    <SOAP:Body>
        <sh:StandardBusinessDocument xmlns:sh="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader" xmlns:order="urn:ean.ucc:order:2" xmlns:eanucc="urn:ean.ucc:2" xmlns:ns0="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <sh:StandardBusinessDocumentHeader>
                <sh:HeaderVersion>2.4.0</sh:HeaderVersion>
                <sh:Sender>
                    <sh:Identifier Authority="EAN.UCC">6001000000001</sh:Identifier>
                </sh:Sender>
                <sh:Receiver>
                    <sh:Identifier Authority="EAN.UCC">6001651048339</sh:Identifier>
                </sh:Receiver>
                <sh:DocumentIdentification>
                    <sh:Standard>EAN.UCC</sh:Standard>
                    <sh:TypeVersion>2.4</sh:TypeVersion>
                    <sh:InstanceIdentifier>0000000055824250</sh:InstanceIdentifier>
                    <sh:Type>ROSTER</sh:Type>
                    <sh:MultipleType>false</sh:MultipleType>
                    <sh:CreationDateAndTime>2010-10-01T10:46:00</sh:CreationDateAndTime>
                </sh:DocumentIdentification>
            </sh:StandardBusinessDocumentHeader>
            <eanucc:message>
                <entityIdentification>
                    <uniqueCreatorIdentification>0410933100</uniqueCreatorIdentification>
                    <contentOwner>
                        <gln>6001000000001</gln>
                    </contentOwner>
                </entityIdentification>
                <eanucc:transaction>
                    <entityIdentification>
                        <uniqueCreatorIdentification>0410933100</uniqueCreatorIdentification>
                        <contentOwner>
                            <gln>6001000000001</gln>
                        </contentOwner>
                    </entityIdentification>
                    <command>
                        <eanucc:documentCommand>
                            <documentCommandHeader type="ADD">
                                <entityIdentification>
                                    <uniqueCreatorIdentification>0410933100</uniqueCreatorIdentification>
                                    <contentOwner>
                                        <gln>6001000000001</gln>
                                    </contentOwner>
                                </entityIdentification>
                            </documentCommandHeader>
                            <documentCommandOperand>
                                <order:order creationDateTime="2010-08-06T00:00:00" documentStatus="ORIGINAL">
                                    <orderIdentification>
                                        <uniqueCreatorIdentification>0410933100</uniqueCreatorIdentification>
                                        <contentOwner>
                                            <gln>6001000000001</gln>
                                            <additionalPartyIdentification>
                                                <additionalPartyIdentificationValue />
                                                <additionalPartyIdentificationType>ROSTER</additionalPartyIdentificationType>
                                            </additionalPartyIdentification>
                                        </contentOwner>
                                    </orderIdentification>
                                    <orderPartyInformation>
                                        <seller>
                                            <gln>6003105000009</gln>
                                            <additionalPartyIdentification>
                                                <additionalPartyIdentificationValue>0010005787</additionalPartyIdentificationValue>
                                                <additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
                                            </additionalPartyIdentification>
                                            <additionalPartyIdentification>
                                                <additionalPartyIdentificationValue>My Company (Pty) Ltd</additionalPartyIdentificationValue>
                                                <additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
                                            </additionalPartyIdentification>
                                            <additionalPartyIdentification>
                                                <additionalPartyIdentificationValue>4788509106</additionalPartyIdentificationValue>
                                                <additionalPartyIdentificationType>SELLER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
                                            </additionalPartyIdentification>
                                        </seller>
                                        <buyer>
                                            <gln>6001007031006</gln>
                                            <additionalPartyIdentification>
                                                <additionalPartyIdentificationValue>Western Cape Corporate</additionalPartyIdentificationValue>
                                                <additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
                                            </additionalPartyIdentification>
                                        </buyer>
                                    </orderPartyInformation>
                                    <orderLogisticalInformation>
                                        <shipToLogistics>
                                            <shipTo>
                                                <gln>6001007031213</gln>
                                                <additionalPartyIdentification>
                                                    <additionalPartyIdentificationValue>WC21</additionalPartyIdentificationValue>
                                                    <additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
                                                </additionalPartyIdentification>
                                                <additionalPartyIdentification>
                                                    <additionalPartyIdentificationValue>Constantia</additionalPartyIdentificationValue>
                                                    <additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
                                                </additionalPartyIdentification>
                                            </shipTo>
                                        </shipToLogistics>
                                        <orderLogisticalDateGroup>
                                            <requestedDeliveryDateAtUltimateConsignee>
                                                <date>2010-08-06</date>
                                            </requestedDeliveryDateAtUltimateConsignee>
                                        </orderLogisticalDateGroup>
                                    </orderLogisticalInformation>
                                    <orderLineItem number="10">
                                        <requestedQuantity>
                                            <value>2.000</value>
                                        </requestedQuantity>
                                        <netPrice>
                                            <amount>
                                                <currencyCode>
                                                    <currencyISOCode>ZAR</currencyISOCode>
                                                </currencyCode>
                                                <monetaryAmount>150.14</monetaryAmount>
                                            </amount>
                                        </netPrice>
                                        <netAmount>
                                            <amount>
                                                <currencyCode>
                                                    <currencyISOCode>ZAR</currencyISOCode>
                                                </currencyCode>
                                                <monetaryAmount>342.32</monetaryAmount>
                                            </amount>
                                        </netAmount>
                                        <tradeItemIdentification>
                                            <gtin>46001452377001</gtin>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>00000</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>ARTICLE 001 1L</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>171576</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>12</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                        </tradeItemIdentification>
                                        <allowanceCharge allowanceChargeType="TRADE_ALLOWANCE" allowanceOrChargeType="ALLOWANCE" sequenceNumber="01" settlementType="OFF_INVOICE">
                                            <monetaryAmountOrPercentage>
                                                <percentage>5.00</percentage>
                                            </monetaryAmountOrPercentage>
                                        </allowanceCharge>
                                    </orderLineItem>
                                    <orderLineItem number="20">
                                        <requestedQuantity>
                                            <value>2.000</value>
                                        </requestedQuantity>
                                        <netPrice>
                                            <amount>
                                                <currencyCode>
                                                    <currencyISOCode>ZAR</currencyISOCode>
                                                </currencyCode>
                                                <monetaryAmount>309.59</monetaryAmount>
                                            </amount>
                                        </netPrice>
                                        <netAmount>
                                            <amount>
                                                <currencyCode>
                                                    <currencyISOCode>ZAR</currencyISOCode>
                                                </currencyCode>
                                                <monetaryAmount>705.86</monetaryAmount>
                                            </amount>
                                        </netAmount>
                                        <tradeItemIdentification>
                                            <gtin>16001452496008</gtin>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>496</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>ARTICLE 002 5L</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>171576</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>4</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                        </tradeItemIdentification>
                                        <allowanceCharge allowanceChargeType="BULK_ALLOWANCE" allowanceOrChargeType="ALLOWANCE" sequenceNumber="01" settlementType="OFF_INVOICE">
                                            <monetaryAmountOrPercentage>
                                                <amount>
                                                    <currencyCode>
                                                        <currencyISOCode>ZAR</currencyISOCode>
                                                    </currencyCode>
                                                    <monetaryAmount>10.00</monetaryAmount>
                                                </amount>
                                            </monetaryAmountOrPercentage>
                                        </allowanceCharge>
                                    </orderLineItem>
                                    <orderLineItem number="30">
                                        <requestedQuantity>
                                            <value>2.000</value>
                                        </requestedQuantity>
                                        <netPrice>
                                            <amount>
                                                <currencyCode>
                                                    <currencyISOCode>ZAR</currencyISOCode>
                                                </currencyCode>
                                                <monetaryAmount>743.86</monetaryAmount>
                                            </amount>
                                        </netPrice>
                                        <netAmount>
                                            <amount>
                                                <currencyCode>
                                                    <currencyISOCode>ZAR</currencyISOCode>
                                                </currencyCode>
                                                <monetaryAmount>1696.00</monetaryAmount>
                                            </amount>
                                        </netAmount>
                                        <tradeItemIdentification>
                                            <gtin>6001496010584</gtin>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>1004101</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>ARTICLE 003 750ML</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>315025</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>12</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                        </tradeItemIdentification>
                                        <allowanceCharge allowanceChargeType="BULK_ALLOWANCE" allowanceOrChargeType="ALLOWANCE" sequenceNumber="01" settlementType="OFF_INVOICE">
                                            <monetaryAmountOrPercentage>
                                                <amount>
                                                    <currencyCode>
                                                        <currencyISOCode>ZAR</currencyISOCode>
                                                    </currencyCode>
                                                    <monetaryAmount>20.00</monetaryAmount>
                                                </amount>
                                            </monetaryAmountOrPercentage>
                                        </allowanceCharge>
                                    </orderLineItem>
                                    <orderLineItem number="40">
                                        <requestedQuantity>
                                            <value>2.000</value>
                                        </requestedQuantity>
                                        <netPrice>
                                            <amount>
                                                <currencyCode>
                                                    <currencyISOCode>ZAR</currencyISOCode>
                                                </currencyCode>
                                                <monetaryAmount>193.12</monetaryAmount>
                                            </amount>
                                        </netPrice>
                                        <netAmount>
                                            <amount>
                                                <currencyCode>
                                                    <currencyISOCode>ZAR</currencyISOCode>
                                                </currencyCode>
                                                <monetaryAmount>440.31</monetaryAmount>
                                            </amount>
                                        </netAmount>
                                        <tradeItemIdentification>
                                            <gtin>46001452632001</gtin>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>0000697</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>ARTICLE 004 750ML</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>315025</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                            <additionalTradeItemIdentification>
                                                <additionalTradeItemIdentificationValue>12</additionalTradeItemIdentificationValue>
                                                <additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
                                            </additionalTradeItemIdentification>
                                        </tradeItemIdentification>
                                        <allowanceCharge allowanceChargeType="TRADE_ALLOWANCE" allowanceOrChargeType="ALLOWANCE" sequenceNumber="01" settlementType="OFF_INVOICE">
                                            <monetaryAmountOrPercentage>
                                                <percentage>5.00</percentage>
                                            </monetaryAmountOrPercentage>
                                        </allowanceCharge>
                                    </orderLineItem>
                                    <orderHeaderIndicator>
                                        <isApplicationReceiptAcknowledgementRequired>true</isApplicationReceiptAcknowledgementRequired>
                                        <isOrderFreeOfExciseTaxDuty>false</isOrderFreeOfExciseTaxDuty>
                                    </orderHeaderIndicator>
                                </order:order>
                            </documentCommandOperand>
                        </eanucc:documentCommand>
                    </command>
                </eanucc:transaction>
            </eanucc:message>
        </sh:StandardBusinessDocument>
    </SOAP:Body>
</SOAP:Envelope>';


?>