<?php 

$headerArr = Array();

$headerArr2 = Array();

$headerArr[] = "vbeln(010),";
$headerArr[] = "zzsotype(002),";   
$headerArr[] = "audat(10),";
$headerArr[] = "auart(004),";
$headerArr[] = "vkorg(004),";
$headerArr[] = "vtweg(002),";
$headerArr[] = "spart(002),";
$headerArr[] = "vkbur(004),";
$headerArr[] = "bstkd(035),";
$headerArr[] = "bstdk(10),";
$headerArr[] = "kunnr(010),";
$headerArr[] = "zlsch(001),";
$headerArr[] = "vbelnd(010),";     
$headerArr[] = "vbelp(005),";
$headerArr[] = "zzexnum(030),";    
$headerArr[] = "matnr(018),";
$headerArr[] = "kwmeng(019),";     
$headerArr[] = "vrkme(004),";
$headerArr[] = "abgru(002),";
$headerArr[] = "werks(004),";  
$headerArr[] = "uebto(004),";
$headerArr[] = "untto(004),";
$headerArr[] = "taxm1(001),";
$headerArr[] = "kschl(004),";
$headerArr[] = "kbetr(016),";
$headerArr[] = "koein(005),";
$headerArr[] = "kpein(005),";
$headerArr[] = "kmein(003),";
$headerArr[] = "fkschl(004),";     
$headerArr[] = "frpri(016),";
$headerArr[] = "frccy(005),";
$headerArr[] = "frper(005),";
$headerArr[] = "fruom(003),";
$headerArr[] = "zterm(004),";
$headerArr[] = "inco1(003),";
$headerArr[] = "inco2(028),";
$headerArr[] = "waerk(005),";
$headerArr[] = "vsbed(002),";
$headerArr[] = "vkgrp(003),";
$headerArr[] = "znot1(72),";
$headerArr[] = "znot2(72),";
$headerArr[] = "znot3(72),";
$headerArr[] = "znot4(72),";
$headerArr[] = "zvsl(10),"; 
$headerArr[] = "voyage(50),";
$headerArr[] = "zlpt(28),"; 
$headerArr[] = "zdpt(28),"; 
$headerArr[] = "zfrp_ccy(05),";    
$headerArr[] = "zfrp(16),"; 
$headerArr[] = "shp_date(30),";    
$headerArr[] = "yesno(001),";
$headerArr[] = "cntr_typ(01),";    
$headerArr[] = "comp_date(72),";   
$headerArr[] = "rc_kschl(004),";   
$headerArr[] = "rcpri(016),";
$headerArr[] = "rcccy(005),";
$headerArr[] = "rcper(005),";
$headerArr[] = "rcuom(003),";
$headerArr[] = "so_num(010),";     
$headerArr[] = "rb_kschl(004),";   
$headerArr[] = "rbamt(018),";
$headerArr[] = "rbccy(005),";
$headerArr[] = "zzdischarge(028),";
$headerArr[] = "zzvremk(002),";    
$headerArr[] = "sorefer(010),";    
$headerArr[] = "zzafce(035),";     
$headerArr[] = "po_item(006),";    
$headerArr[] = "zzvalidfrom(10),"; 
$headerArr[] = "zzvalidto(10),";   
$headerArr[] = "zzwarehouse(10),"; 
$headerArr[] = "Location";  
$headerArr[] = "NPWP Item";
  
   
$headerArr2[] = "Item Indicator";
$headerArr2[] = "";   
$headerArr2[] = "Document date"; 
$headerArr2[] = "Document type"; 
$headerArr2[] = "Sales Organization";   
$headerArr2[] = "Distribution channel"; 
$headerArr2[] = "Division";  
$headerArr2[] = "Sales Office";  
$headerArr2[] = "PO number"; 
$headerArr2[] = "PO date";   
$headerArr2[] = "Customer code"; 
$headerArr2[] = "Payment method";
$headerArr2[] = "";   
$headerArr2[] = "SO item";   
$headerArr2[] = "";   
$headerArr2[] = "Material Code"; 
$headerArr2[] = "Order Qty"; 
$headerArr2[] = "Order UoM"; 
$headerArr2[] = "Reason for rejection"; 
$headerArr2[] = "Plant";     
$headerArr2[] = "Over tolerance";
$headerArr2[] = "Under tolerance";
$headerArr2[] = "Tax class 1";   
$headerArr2[] = "Condition Type";
$headerArr2[] = "Amount";    
$headerArr2[] = "Currency";  
$headerArr2[] = "Per";
$headerArr2[] = "UoM";
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "Payment terms"; 
$headerArr2[] = "Inco1";     
$headerArr2[] = "Inco2";     
$headerArr2[] = "Currency";  
$headerArr2[] = "Shipping condition";   
$headerArr2[] = "Sales group";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "SO number"; 
$headerArr2[] = "";
$headerArr2[] = "";
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "";   
$headerArr2[] = "AFCE No";   
$headerArr2[] = "";      //  1   
$headerArr2[] = "";      //  2
$headerArr2[] = "";      //  3          
$headerArr2[] = "";      //  4
$headerArr2[] = "";      //  5
$headerArr2[] = "";      //  6
$headerArr2[] = "";      //  7      
$headerArr2[] = "";      //  8      
$headerArr2[] = "";      //  9      
$headerArr2[] = "";      //  0      
$headerArr2[] = "";      //  1      
$headerArr2[] = "";      //  2      
$headerArr2[] = "";      //  3      
$headerArr2[] = "";      //  4      
$headerArr2[] = "";      //  5      
$headerArr2[] = "";      //  6     
$headerArr2[] = "Reference";      //  7  

$creditNoteArr = Array();

$creditNoteArr[] = 'SALES ORDER TYPE';             // 1
$creditNoteArr[] = 'SALES ORGANIZATION';           // 2
$creditNoteArr[] = 'DISTRIBUTION CHANNEL';         // 3
$creditNoteArr[] = 'DIVISION';                     // 4
$creditNoteArr[] = 'SALES OFFICE';                 // 5
$creditNoteArr[] = 'SALES GROUP';                  // 6
$creditNoteArr[] = 'SOLD TO PARTY';                // 7
$creditNoteArr[] = 'DOCUMENT DATE';                // 8
$creditNoteArr[] = 'BILLING DATE';                 // 9
$creditNoteArr[] = 'ORDER REASON';                 // 10
$creditNoteArr[] = 'TERM OF PAYMENT';              // 11
$creditNoteArr[] = 'PRICE LIST';                   // 12
$creditNoteArr[] = 'PRICE GROUP';                  // 13
$creditNoteArr[] = 'SALES DISTRICT';               // 14
$creditNoteArr[] = 'INCOTERM1';                    // 15
$creditNoteArr[] = 'INCOTERM2';                    // 16
$creditNoteArr[] = 'PO NO';                        // 17
$creditNoteArr[] = 'PO DATE';                      // 18
$creditNoteArr[] = 'ITEM';                         // 19
$creditNoteArr[] = 'MATERIAL';                     // 20
$creditNoteArr[] = 'QTY';                          // 21
$creditNoteArr[] = 'UOM';                          // 22
$creditNoteArr[] = 'PLANT';                        // 23
$creditNoteArr[] = 'PRICE';                        // 24
$creditNoteArr[] = 'CURRENCY';                     // 25
$creditNoteArr[] = 'TAX TERM';                     // 26
$creditNoteArr[] = 'REFERENCE NO (HEADER TEXT)';   // 27


$headerArrCr = Array(); 

$headerArrCr[] = "vbeln(010),";              // 1 
$headerArrCr[] = "zzsotype(002),";           // 2 
$headerArrCr[] = "audat(10),";               // 3 
$headerArrCr[] = "auart(004),";              // 4 
$headerArrCr[] = "vkorg(004),";              // 5 
$headerArrCr[] = "vtweg(002), ";             // 6 
$headerArrCr[] = "spart(002), ";             // 7 
$headerArrCr[] = "vkbur(004), ";             // 8 
$headerArrCr[] = "bstkd(035), ";             // 9 
$headerArrCr[] = "bstdk(10), ";              // 10
$headerArrCr[] = "kunnr(010), ";             // 11
$headerArrCr[] = "zlsch(001), ";             // 12
$headerArrCr[] = "vbelnd(010), ";            // 13
$headerArrCr[] = "vbelp(005), ";             // 14
$headerArrCr[] = "zzexnum(030), ";           // 15
$headerArrCr[] = "matnr(018), ";             // 16
$headerArrCr[] = "kwmeng(019), ";            // 17
$headerArrCr[] = "vrkme(004), ";             // 18
$headerArrCr[] = "abgru(002), ";             // 19
$headerArrCr[] = "werks(004), ";             // 20
$headerArrCr[] = "uebto(004), ";             // 21
$headerArrCr[] = "untto(004), ";             // 22
$headerArrCr[] = "taxm1(001), ";             // 23
$headerArrCr[] = "kschl(004), ";             // 24
$headerArrCr[] = "kbetr(016), ";             // 25
$headerArrCr[] = "koein(005), ";             // 26
$headerArrCr[] = "kpein(005), ";             // 27
$headerArrCr[] = "kmein(003), ";             // 28 
$headerArrCr[] = "fkschl(004), ";            // 29 
$headerArrCr[] = "frpri(016), ";             // 30 
$headerArrCr[] = "frccy(005), ";             // 31 
$headerArrCr[] = "frper(005), ";             // 32 
$headerArrCr[] = "fruom(003), ";             // 33 
$headerArrCr[] = "zterm(004), ";             // 34 
$headerArrCr[] = "inco1(003), ";             // 35 
$headerArrCr[] = "inco2(028), ";             // 36 
$headerArrCr[] = "waerk(005), ";             // 37
$headerArrCr[] = "vsbed(002), ";             // 38
$headerArrCr[] = "vkgrp(003), ";             // 39
$headerArrCr[] = "znot1(72), ";              // 40
$headerArrCr[] = "znot2(72), ";              // 41
$headerArrCr[] = "znot3(72), ";              // 42
$headerArrCr[] = "znot4(72), ";              // 43
$headerArrCr[] = "zvsl(10), ";               // 44
$headerArrCr[] = "voyage(50), ";             // 45
$headerArrCr[] = "zlpt(28), ";               // 46
$headerArrCr[] = "zdpt(28), ";               // 47
$headerArrCr[] = "zfrp_ccy(05), ";           // 48
$headerArrCr[] = "zfrp(16), ";               // 49
$headerArrCr[] = "shp_date(30), ";           // 50
$headerArrCr[] = "yesno(001), ";             // 51
$headerArrCr[] = "cntr_typ(01), ";           // 53
$headerArrCr[] = "comp_date(72), ";          // 53
$headerArrCr[] = "rc_kschl(004), ";          // 54
$headerArrCr[] = "rcpri(016), ";             // 55
$headerArrCr[] = "rcccy(005), ";             // 56
$headerArrCr[] = "rcper(005), ";             // 57
$headerArrCr[] = "rcuom(003), ";             // 58
$headerArrCr[] = "so_num(010), ";            // 59
$headerArrCr[] = "rb_kschl(004), ";          // 60
$headerArrCr[] = "rbamt(018), ";             // 61
$headerArrCr[] = "rbccy(005), ";             // 63
$headerArrCr[] = "zzdischarge(028), ";       // 63
$headerArrCr[] = "zzvremk(002), ";           // 64
$headerArrCr[] = "sorefer(010), ";           // 65 
$headerArrCr[] = "zzafce(035), ";            // 66 
$headerArrCr[] = "po_item(006), ";           // 67 
$headerArrCr[] = "zzvalidfrom(10), ";        // 68 
$headerArrCr[] = "zzvalidto(10), ";          // 69 
$headerArrCr[] = "zzwarehouse(10),";         // 70 
$headerArrCr[] = "Location ";                // 71
$headerArrCr[] = "NPWP Item";                // 72


$headerArrCr2 = Array(); 

$headerArrCr2[] = "Item Indicator";                           // 1
$headerArrCr2[] = "";                                         // 2
$headerArrCr2[] = "Document date";                            // 3
$headerArrCr2[] = "Document type";                            // 4
$headerArrCr2[] = "Sales Organization";                       // 5
$headerArrCr2[] = "Distribution channel";                     // 6
$headerArrCr2[] = "Division";                                 // 7
$headerArrCr2[] = "Sales Office";                             // 8
$headerArrCr2[] = "PO number";                                // 9
$headerArrCr2[] = "PO date";                                  // 10
$headerArrCr2[] = "Customer code";                            // 11
$headerArrCr2[] = "Payment method";                           // 12
$headerArrCr2[] = "";                                         // 13
$headerArrCr2[] = "SO item";                                  // 14
$headerArrCr2[] = "";                                         // 15
$headerArrCr2[] = "Material Code";                            // 16
$headerArrCr2[] = "Order Qty";                                // 17
$headerArrCr2[] = "Order UoM";                                // 18
$headerArrCr2[] = "Reason for rejection";                     // 19
$headerArrCr2[] = "Plant";                                    // 20
$headerArrCr2[] = "Over tolerance";                           // 21
$headerArrCr2[] = "Under tolerance";                          // 22
$headerArrCr2[] = "Tax class 1";                              // 23
$headerArrCr2[] = "Condition Type";                           // 24
$headerArrCr2[] = "Amount";                                   // 25
$headerArrCr2[] = "Currency";                                 // 26
$headerArrCr2[] = "Per";                                      // 27
$headerArrCr2[] = "UoM";                                      // 28
$headerArrCr2[] = "";                                         // 29
$headerArrCr2[] = "";                                         // 30
$headerArrCr2[] = "";                                         // 31
$headerArrCr2[] = "";                                         // 32
$headerArrCr2[] = "";                                         // 33
$headerArrCr2[] = "Payment terms";                            // 34
$headerArrCr2[] = "Inco1";                                    // 35
$headerArrCr2[] = "Inco2";                                    // 36
$headerArrCr2[] = "Currency";                                 // 37
$headerArrCr2[] = "Shipping condition";                       // 38
$headerArrCr2[] = "Sales group";                              // 39
$headerArrCr2[] = "";                                         // 41
$headerArrCr2[] = "";                                         // 42
$headerArrCr2[] = "";                                         // 43
$headerArrCr2[] = "";                                         // 44
$headerArrCr2[] = "";                                         // 45
$headerArrCr2[] = "";                                         // 46
$headerArrCr2[] = "";                                         // 47
$headerArrCr2[] = "";                                         // 48
$headerArrCr2[] = "";                                         // 49
$headerArrCr2[] = "";                                         // 50
$headerArrCr2[] = "SO number";                                // 51
$headerArrCr2[] = "";                                         // 52
$headerArrCr2[] = "";                                         // 53
$headerArrCr2[] = "";                                         // 53
$headerArrCr2[] = "";                                         // 54
$headerArrCr2[] = "";                                         // 55
$headerArrCr2[] = "";                                         // 56
$headerArrCr2[] = "";                                         // 57
$headerArrCr2[] = "";                                         // 58
$headerArrCr2[] = "";                                         // 59
$headerArrCr2[] = "";                                         // 60
$headerArrCr2[] = "";                                         // 61
$headerArrCr2[] = "";                                         // 63
$headerArrCr2[] = "";                                         // 63
$headerArrCr2[] = "";                                         // 64
$headerArrCr2[] = "";                                         // 65
$headerArrCr2[] = "AFCE No";                                  // 66
$headerArrCr2[] = "";      //  1   
$headerArrCr2[] = "";      //  2
$headerArrCr2[] = "";      //  3          
$headerArrCr2[] = "";      //  4
$headerArrCr2[] = "";      //  5
$headerArrCr2[] = "";      //  6
$headerArrCr2[] = "";      //  7      
$headerArrCr2[] = "";      //  8      
$headerArrCr2[] = "";      //  9      
$headerArrCr2[] = "";      //  0      
$headerArrCr2[] = "";      //  1      
$headerArrCr2[] = "";      //  2      
$headerArrCr2[] = "";      //  3      
$headerArrCr2[] = "";      //  4      
$headerArrCr2[] = "";      //  5      
$headerArrCr2[] = "";      //  6     
$headerArrCr2[] = "Reference";      //  7  