<?php
/**
 * InvoicesByExternalIDApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SkynamoClientAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skynamo Public API
 *
 * The specification for Skynamo's public API <br><br>Helpful links<br> <a href=\"https://support.skynamo.com/hc/en-us/articles/6671335262749-Creating-a-Public-API-Key\" id=\"hint_box\">Creating a Public API Key</a><br> <a href=\"https://support.skynamo.com/hc/en-us/articles/6671463933597-Postman-Examples\" id=\"hint_box\">Postman examples</a><br> <a href=\"https://support.skynamo.com/hc/en-us/articles/6671240071453-How-to-upload-customer-images-using-Postman\" id=\"hint_box\">How to upload customer images</a>
 *
 * The version of the OpenAPI document: 1.0.18
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SkynamoClientAPI\Test\Api;

use \SkynamoClientAPI\Configuration;
use \SkynamoClientAPI\ApiException;
use \SkynamoClientAPI\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InvoicesByExternalIDApiTest Class Doc Comment
 *
 * @category Class
 * @package  SkynamoClientAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvoicesByExternalIDApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for invoicesbyexternalidDelete
     *
     * Delete existing invoices.
     *
     */
    public function testInvoicesbyexternalidDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesbyexternalidExternalIDGet
     *
     * Get an invoice.
     *
     */
    public function testInvoicesbyexternalidExternalIDGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesbyexternalidPatch
     *
     * Update invoices.
     *
     */
    public function testInvoicesbyexternalidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesbyexternalidPost
     *
     * Create invoices.
     *
     */
    public function testInvoicesbyexternalidPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoicesbyexternalidPut
     *
     * Replace invoices.
     *
     */
    public function testInvoicesbyexternalidPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
