<?php
/**
 * Customer
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  SkynamoClientAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skynamo Public API
 *
 * The specification for Skynamo's public API <br><br>Helpful links<br> <a href=\"https://support.skynamo.com/hc/en-us/articles/6671335262749-Creating-a-Public-API-Key\" id=\"hint_box\">Creating a Public API Key</a><br> <a href=\"https://support.skynamo.com/hc/en-us/articles/6671463933597-Postman-Examples\" id=\"hint_box\">Postman examples</a><br> <a href=\"https://support.skynamo.com/hc/en-us/articles/6671240071453-How-to-upload-customer-images-using-Postman\" id=\"hint_box\">How to upload customer images</a>
 *
 * The version of the OpenAPI document: 1.0.18
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SkynamoClientAPI\Model;

use \ArrayAccess;
use \SkynamoClientAPI\ObjectSerializer;

/**
 * Customer Class Doc Comment
 *
 * @category Class
 * @description This is a customer in Skynamo, used for fetching information about customers
 * @package  SkynamoClientAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Customer implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Customer';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'code' => 'string',
        'name' => 'string',
        'active' => 'bool',
        'location' => '\SkynamoClientAPI\Model\Location',
        'price_list_id' => 'int',
        'price_list_name' => 'string',
        'assigned_users' => 'int[]',
        'default_discount' => 'float',
        'default_warehouse_id' => 'int',
        'default_warehouse_name' => 'int',
        'row_version' => 'float',
        'last_modified_time' => '\DateTime',
        'create_date' => '\DateTime',
        'custom_fields' => '\SkynamoClientAPI\Model\CustomField[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'code' => null,
        'name' => null,
        'active' => null,
        'location' => null,
        'price_list_id' => null,
        'price_list_name' => null,
        'assigned_users' => null,
        'default_discount' => 'float',
        'default_warehouse_id' => null,
        'default_warehouse_name' => null,
        'row_version' => 'long',
        'last_modified_time' => 'date-time',
        'create_date' => 'date-time',
        'custom_fields' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'code' => 'code',
        'name' => 'name',
        'active' => 'active',
        'location' => 'location',
        'price_list_id' => 'price_list_id',
        'price_list_name' => 'price_list_name',
        'assigned_users' => 'assigned_users',
        'default_discount' => 'default_discount',
        'default_warehouse_id' => 'default_warehouse_id',
        'default_warehouse_name' => 'default_warehouse_name',
        'row_version' => 'row_version',
        'last_modified_time' => 'last_modified_time',
        'create_date' => 'create_date',
        'custom_fields' => 'custom_fields'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'code' => 'setCode',
        'name' => 'setName',
        'active' => 'setActive',
        'location' => 'setLocation',
        'price_list_id' => 'setPriceListId',
        'price_list_name' => 'setPriceListName',
        'assigned_users' => 'setAssignedUsers',
        'default_discount' => 'setDefaultDiscount',
        'default_warehouse_id' => 'setDefaultWarehouseId',
        'default_warehouse_name' => 'setDefaultWarehouseName',
        'row_version' => 'setRowVersion',
        'last_modified_time' => 'setLastModifiedTime',
        'create_date' => 'setCreateDate',
        'custom_fields' => 'setCustomFields'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'code' => 'getCode',
        'name' => 'getName',
        'active' => 'getActive',
        'location' => 'getLocation',
        'price_list_id' => 'getPriceListId',
        'price_list_name' => 'getPriceListName',
        'assigned_users' => 'getAssignedUsers',
        'default_discount' => 'getDefaultDiscount',
        'default_warehouse_id' => 'getDefaultWarehouseId',
        'default_warehouse_name' => 'getDefaultWarehouseName',
        'row_version' => 'getRowVersion',
        'last_modified_time' => 'getLastModifiedTime',
        'create_date' => 'getCreateDate',
        'custom_fields' => 'getCustomFields'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['code'] = $data['code'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['active'] = $data['active'] ?? true;
        $this->container['location'] = $data['location'] ?? null;
        $this->container['price_list_id'] = $data['price_list_id'] ?? null;
        $this->container['price_list_name'] = $data['price_list_name'] ?? null;
        $this->container['assigned_users'] = $data['assigned_users'] ?? null;
        $this->container['default_discount'] = $data['default_discount'] ?? 0.0;
        $this->container['default_warehouse_id'] = $data['default_warehouse_id'] ?? null;
        $this->container['default_warehouse_name'] = $data['default_warehouse_name'] ?? null;
        $this->container['row_version'] = $data['row_version'] ?? null;
        $this->container['last_modified_time'] = $data['last_modified_time'] ?? null;
        $this->container['create_date'] = $data['create_date'] ?? null;
        $this->container['custom_fields'] = $data['custom_fields'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id The unique id of the customer
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code The unique code associated with this customer
     *
     * @return self
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The name of the customer
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets active
     *
     * @return bool|null
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool|null $active Whether or not the customer is active
     *
     * @return self
     */
    public function setActive($active)
    {
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets location
     *
     * @return \SkynamoClientAPI\Model\Location|null
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param \SkynamoClientAPI\Model\Location|null $location location
     *
     * @return self
     */
    public function setLocation($location)
    {
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets price_list_id
     *
     * @return int|null
     */
    public function getPriceListId()
    {
        return $this->container['price_list_id'];
    }

    /**
     * Sets price_list_id
     *
     * @param int|null $price_list_id The unique identifier of the price list associated with this customer
     *
     * @return self
     */
    public function setPriceListId($price_list_id)
    {
        $this->container['price_list_id'] = $price_list_id;

        return $this;
    }

    /**
     * Gets price_list_name
     *
     * @return string|null
     */
    public function getPriceListName()
    {
        return $this->container['price_list_name'];
    }

    /**
     * Sets price_list_name
     *
     * @param string|null $price_list_name The name of the price list associated with this customer
     *
     * @return self
     */
    public function setPriceListName($price_list_name)
    {
        $this->container['price_list_name'] = $price_list_name;

        return $this;
    }

    /**
     * Gets assigned_users
     *
     * @return int[]|null
     */
    public function getAssignedUsers()
    {
        return $this->container['assigned_users'];
    }

    /**
     * Sets assigned_users
     *
     * @param int[]|null $assigned_users List of user ids that are assigned to this customer
     *
     * @return self
     */
    public function setAssignedUsers($assigned_users)
    {
        $this->container['assigned_users'] = $assigned_users;

        return $this;
    }

    /**
     * Gets default_discount
     *
     * @return float|null
     */
    public function getDefaultDiscount()
    {
        return $this->container['default_discount'];
    }

    /**
     * Sets default_discount
     *
     * @param float|null $default_discount The default discount applied for this customer when creating orders
     *
     * @return self
     */
    public function setDefaultDiscount($default_discount)
    {
        $this->container['default_discount'] = $default_discount;

        return $this;
    }

    /**
     * Gets default_warehouse_id
     *
     * @return int|null
     */
    public function getDefaultWarehouseId()
    {
        return $this->container['default_warehouse_id'];
    }

    /**
     * Sets default_warehouse_id
     *
     * @param int|null $default_warehouse_id The unique identifier of the warehouse associated with this customer
     *
     * @return self
     */
    public function setDefaultWarehouseId($default_warehouse_id)
    {
        $this->container['default_warehouse_id'] = $default_warehouse_id;

        return $this;
    }

    /**
     * Gets default_warehouse_name
     *
     * @return int|null
     */
    public function getDefaultWarehouseName()
    {
        return $this->container['default_warehouse_name'];
    }

    /**
     * Sets default_warehouse_name
     *
     * @param int|null $default_warehouse_name The name of the warehouse associated with this customer
     *
     * @return self
     */
    public function setDefaultWarehouseName($default_warehouse_name)
    {
        $this->container['default_warehouse_name'] = $default_warehouse_name;

        return $this;
    }

    /**
     * Gets row_version
     *
     * @return float|null
     */
    public function getRowVersion()
    {
        return $this->container['row_version'];
    }

    /**
     * Sets row_version
     *
     * @param float|null $row_version An automatically generated, unique number used to version-stamp table rows in the database
     *
     * @return self
     */
    public function setRowVersion($row_version)
    {
        $this->container['row_version'] = $row_version;

        return $this;
    }

    /**
     * Gets last_modified_time
     *
     * @return \DateTime|null
     */
    public function getLastModifiedTime()
    {
        return $this->container['last_modified_time'];
    }

    /**
     * Sets last_modified_time
     *
     * @param \DateTime|null $last_modified_time The last time this customer was modified
     *
     * @return self
     */
    public function setLastModifiedTime($last_modified_time)
    {
        $this->container['last_modified_time'] = $last_modified_time;

        return $this;
    }

    /**
     * Gets create_date
     *
     * @return \DateTime|null
     */
    public function getCreateDate()
    {
        return $this->container['create_date'];
    }

    /**
     * Sets create_date
     *
     * @param \DateTime|null $create_date The time at which this customer was created
     *
     * @return self
     */
    public function setCreateDate($create_date)
    {
        $this->container['create_date'] = $create_date;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return \SkynamoClientAPI\Model\CustomField[]|null
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param \SkynamoClientAPI\Model\CustomField[]|null $custom_fields Certain custom fields may be required depending on the custom fields that have been set up
     *
     * @return self
     */
    public function setCustomFields($custom_fields)
    {
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


